/*
 * This file is generated by jOOQ.
 */
package com.github.uuidcode.jooq.test.jooq;


import com.github.uuidcode.jooq.test.jooq.tables.QBook;
import com.github.uuidcode.jooq.test.jooq.tables.QUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QJooq extends SchemaImpl {

    private static final long serialVersionUID = -1400088229;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final QJooq JOOQ = new QJooq();

    /**
     * The table <code>jooq.book</code>.
     */
    public final QBook BOOK = com.github.uuidcode.jooq.test.jooq.tables.QBook.BOOK;

    /**
     * The table <code>jooq.user</code>.
     */
    public final QUser USER = com.github.uuidcode.jooq.test.jooq.tables.QUser.USER;

    /**
     * No further instances allowed
     */
    private QJooq() {
        super("jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            QBook.BOOK,
            QUser.USER);
    }
}
