/*
 * This file is generated by jOOQ.
 */
package com.github.uuidcode.jooq.test.jooq;


import com.github.uuidcode.jooq.test.jooq.tables.QBook;
import com.github.uuidcode.jooq.test.jooq.tables.QUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.book</code>.
     */
    public static final QBook BOOK = com.github.uuidcode.jooq.test.jooq.tables.QBook.BOOK;

    /**
     * The table <code>jooq.user</code>.
     */
    public static final QUser USER = com.github.uuidcode.jooq.test.jooq.tables.QUser.USER;
}
