/*
 * This file is generated by jOOQ.
 */
package com.github.uuidcode.jooq.test.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 802334882;

    private Long      bookId;
    private String    name;
    private Timestamp regDatetime;
    private Long      userId;

    public Book() {}

    public Book(Book value) {
        this.bookId = value.bookId;
        this.name = value.name;
        this.regDatetime = value.regDatetime;
        this.userId = value.userId;
    }

    public Book(
        Long      bookId,
        String    name,
        Timestamp regDatetime,
        Long      userId
    ) {
        this.bookId = bookId;
        this.name = name;
        this.regDatetime = regDatetime;
        this.userId = userId;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getRegDatetime() {
        return this.regDatetime;
    }

    public void setRegDatetime(Timestamp regDatetime) {
        this.regDatetime = regDatetime;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(bookId);
        sb.append(", ").append(name);
        sb.append(", ").append(regDatetime);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
