/*
 * This file is generated by jOOQ.
 */
package com.github.uuidcode.jooq.test.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 244080208;

    private Long      userId;
    private String    name;
    private Timestamp regDatetime;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.name = value.name;
        this.regDatetime = value.regDatetime;
    }

    public User(
        Long      userId,
        String    name,
        Timestamp regDatetime
    ) {
        this.userId = userId;
        this.name = name;
        this.regDatetime = regDatetime;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getRegDatetime() {
        return this.regDatetime;
    }

    public void setRegDatetime(Timestamp regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
